name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g pnpm
      - uses: actions/checkout@v3
      - run: make lint
