name: publish

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g pnpm
      - run: pnpm i
      - run: make lint
  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g pnpm
      - run: pnpm i
      - run: pnpm build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "./build"
      - uses: actions/deploy-pages@v1
        id: deployment
